server:
  port: 8080
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: host_route
          uri: lb://AUTHENTICATION-SERVICE/
          predicates:
            - Path= /login

        - id: register_route
          uri: lb://AUTHENTICATION-SERVICE/
          predicates:
            - Path= /register

        - id: register_route
          uri: lb://AUTHENTICATION-SERVICE/
          predicates:
            - Path= /welcome

        - id: user_route
          uri: lb://MEETING-SERVICE/
          predicates:
            - Path=/meeting/alreadyDealedNotifications

        - id: user_route
          uri: lb://AUTHENTICATION-SERVICE/
          predicates:
            - Path=/user/**

        - id: admin_route
          uri: lb://MEETING-SERVICE/
          predicates:
            - Path=/admin/**

        - id: meeting_route
          uri: lb://MEETING-SERVICE/
          predicates:
            - Path=/meeting/**

        - id: article_route
          uri: lb://ARTICLE-SERVICE/
          predicates:
            - Path=/article/**
